// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version:4.0.30319.42000
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Diagnostics;
using System.Runtime.CompilerServices;




namespace ToDoModel.My
{

    [CompilerGenerated()]
    [System.CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
    internal sealed partial class MySettings : System.Configuration.ApplicationSettingsBase
    {

        private static MySettings defaultInstance = (MySettings)Synchronized(new MySettings());

        #region My.Settings Auto-Save Functionality
        /* TODO ERROR: Skipped IfDirectiveTrivia
        #If _MyType = "WindowsForms" Then
        *//* TODO ERROR: Skipped DisabledTextTrivia
            Private Shared addedHandler As Boolean

            Private Shared addedHandlerLockObject As New Object

            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
            Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
                If My.Application.SaveMySettingsOnExit Then
                    My.Settings.Save()
                End If
            End Sub
        *//* TODO ERROR: Skipped EndIfDirectiveTrivia
        #End If
        */
        #endregion

        public static MySettings Default
        {
            get
            {

                /* TODO ERROR: Skipped IfDirectiveTrivia
                #If _MyType = "WindowsForms" Then
                *//* TODO ERROR: Skipped DisabledTextTrivia
                               If Not addedHandler Then
                                    SyncLock addedHandlerLockObject
                                        If Not addedHandler Then
                                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                                            addedHandler = True
                                        End If
                                    End SyncLock
                                End If
                *//* TODO ERROR: Skipped EndIfDirectiveTrivia
                #End If
                */
                return defaultInstance;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("Tag PPL ")]
        public string Prefix_People
        {
            get
            {
                return (string)(this["Prefix_People"]);
            }
            set
            {
                this["Prefix_People"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("_@")]
        public string Prefix_Context
        {
            get
            {
                return (string)(this["Prefix_Context"]);
            }
            set
            {
                this["Prefix_Context"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("Tag TOPIC ")]
        public string Prefix_Topic
        {
            get
            {
                return (string)(this["Prefix_Topic"]);
            }
            set
            {
                this["Prefix_Topic"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("Tag PROJECT ")]
        public string Prefix_Project
        {
            get
            {
                return Conversions.ToString(this["Prefix_Project"]);
            }
            set
            {
                this["Prefix_Project"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("Tag A Top Priority Today")]
        public string Prefix_Today
        {
            get
            {
                return Conversions.ToString(this["Prefix_Today"]);
            }
            set
            {
                this["Prefix_Today"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("Tag Bullpin Priorities")]
        public string Prefix_Bullpin
        {
            get
            {
                return Conversions.ToString(this["Prefix_Bullpin"]);
            }
            set
            {
                this["Prefix_Bullpin"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("Tag KB ")]
        public string Prefix_KB
        {
            get
            {
                return Conversions.ToString(this["Prefix_KB"]);
            }
            set
            {
                this["Prefix_KB"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("15")]
        public string Default_Task_Length
        {
            get
            {
                return Conversions.ToString(this["Default_Task_Length"]);
            }
            set
            {
                this["Default_Task_Length"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0")]
        public long MaxToDo
        {
            get
            {
                return Conversions.ToLong(this["MaxToDo"]);
            }
            set
            {
                this["MaxToDo"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("10")]
        public int MaxIDLength
        {
            get
            {
                return Conversions.ToInteger(this["MaxIDLength"]);
            }
            set
            {
                this["MaxIDLength"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("3")]
        public int MaxFolders_ConvID
        {
            get
            {
                return Conversions.ToInteger(this["MaxFolders_ConvID"]);
            }
            set
            {
                this["MaxFolders_ConvID"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("9999999CTF_Inc.txt")]
        public string File_CTF_Inc
        {
            get
            {
                return Conversions.ToString(this["File_CTF_Inc"]);
            }
            set
            {
                this["File_CTF_Inc"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("9999999CTF_Map.txt")]
        public string File_CTF_Map
        {
            get
            {
                return Conversions.ToString(this["File_CTF_Map"]);
            }
            set
            {
                this["File_CTF_Map"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("9999999Subject_Map.txt")]
        public string File_Subject_Map
        {
            get
            {
                return Conversions.ToString(this["File_Subject_Map"]);
            }
            set
            {
                this["File_Subject_Map"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("9999999CommonWords.txt")]
        public string File_Common_Words
        {
            get
            {
                return Conversions.ToString(this["File_Common_Words"]);
            }
            set
            {
                this["File_Common_Words"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("999999ConditionalReminders.txt")]
        public string File_ConditionalReminders
        {
            get
            {
                return Conversions.ToString(this["File_ConditionalReminders"]);
            }
            set
            {
                this["File_ConditionalReminders"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("3")]
        public int MaxFolders_Subject
        {
            get
            {
                return Conversions.ToInteger(this["MaxFolders_Subject"]);
            }
            set
            {
                this["MaxFolders_Subject"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("5")]
        public int MaxSuggestions
        {
            get
            {
                return Conversions.ToInteger(this["MaxSuggestions"]);
            }
            set
            {
                this["MaxSuggestions"] = value;
            }
        }
    }
}

namespace ToDoModel.My
{

    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal static class MySettingsProperty
    {

        [System.ComponentModel.Design.HelpKeyword("My.Settings")]
        internal static MySettings Settings
        {
            get
            {
                return MySettings.Default;
            }
        }
    }
}