//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskMaster.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MaxToDo {
            get {
                return ((int)(this["MaxToDo"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int Default_Task_Length {
            get {
                return ((int)(this["Default_Task_Length"]));
            }
            set {
                this["Default_Task_Length"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tag PPL ")]
        public string Prefix_People {
            get {
                return ((string)(this["Prefix_People"]));
            }
            set {
                this["Prefix_People"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_@")]
        public string Prefix_Context {
            get {
                return ((string)(this["Prefix_Context"]));
            }
            set {
                this["Prefix_Context"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tag TOPIC ")]
        public string Prefix_Topic {
            get {
                return ((string)(this["Prefix_Topic"]));
            }
            set {
                this["Prefix_Topic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tag PROJECT ")]
        public string Prefix_Project {
            get {
                return ((string)(this["Prefix_Project"]));
            }
            set {
                this["Prefix_Project"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tag A Top Priority Today")]
        public string Prefix_Today {
            get {
                return ((string)(this["Prefix_Today"]));
            }
            set {
                this["Prefix_Today"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tag Bullpin Priorities")]
        public string Prefix_Bullpin {
            get {
                return ((string)(this["Prefix_Bullpin"]));
            }
            set {
                this["Prefix_Bullpin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tag KB ")]
        public string Prefix_KB {
            get {
                return ((string)(this["Prefix_KB"]));
            }
            set {
                this["Prefix_KB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Archive")]
        public string Archive_Root {
            get {
                return ((string)(this["Archive_Root"]));
            }
            set {
                this["Archive_Root"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ProjInfo.json")]
        public string FileName_ProjInfo {
            get {
                return ((string)(this["FileName_ProjInfo"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pplkey.json")]
        public string FilenameDictPpl {
            get {
                return ((string)(this["FilenameDictPpl"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UsedIDList.json")]
        public string FileName_IDList {
            get {
                return ((string)(this["FileName_IDList"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("dictRemap.csv")]
        public string FileName_DictRemap {
            get {
                return ((string)(this["FileName_DictRemap"]));
            }
            set {
                this["FileName_DictRemap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int ConversationExponent {
            get {
                return ((int)(this["ConversationExponent"]));
            }
            set {
                this["ConversationExponent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10000")]
        public int ConversationWeight {
            get {
                return ((int)(this["ConversationWeight"]));
            }
            set {
                this["ConversationWeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SubjectExponent {
            get {
                return ((int)(this["SubjectExponent"]));
            }
            set {
                this["SubjectExponent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int SmithWatterman_GapPenalty {
            get {
                return ((int)(this["SmithWatterman_GapPenalty"]));
            }
            set {
                this["SmithWatterman_GapPenalty"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int SmithWatterman_MatchScore {
            get {
                return ((int)(this["SmithWatterman_MatchScore"]));
            }
            set {
                this["SmithWatterman_MatchScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SmithWatterman_MismatchScore {
            get {
                return ((int)(this["SmithWatterman_MismatchScore"]));
            }
            set {
                this["SmithWatterman_MismatchScore"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MaxRecents {
            get {
                return ((int)(this["MaxRecents"]));
            }
            set {
                this["MaxRecents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999999RecentsFile.json")]
        public string FileName_Recents {
            get {
                return ((string)(this["FileName_Recents"]));
            }
            set {
                this["FileName_Recents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999999CTF_Inc.json")]
        public string File_CTF_Inc {
            get {
                return ((string)(this["File_CTF_Inc"]));
            }
            set {
                this["File_CTF_Inc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999999CTF_Map.json")]
        public string File_CTF_Map {
            get {
                return ((string)(this["File_CTF_Map"]));
            }
            set {
                this["File_CTF_Map"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999999Subject_Map.json")]
        public string File_Subject_Map {
            get {
                return ((string)(this["File_Subject_Map"]));
            }
            set {
                this["File_Subject_Map"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999999CommonWords.json")]
        public string File_Common_Words {
            get {
                return ((string)(this["File_Common_Words"]));
            }
            set {
                this["File_Common_Words"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("999999ConditionalReminders.json")]
        public string File_ConditionalReminders {
            get {
                return ((string)(this["File_ConditionalReminders"]));
            }
            set {
                this["File_ConditionalReminders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("999999CategoryFilters.json")]
        public string FileName_CategoryFilters {
            get {
                return ((string)(this["FileName_CategoryFilters"]));
            }
            set {
                this["FileName_CategoryFilters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Main View")]
        public string View_Wide {
            get {
                return ((string)(this["View_Wide"]));
            }
            set {
                this["View_Wide"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Compact")]
        public string View_Compact {
            get {
                return ((string)(this["View_Compact"]));
            }
            set {
                this["View_Compact"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999999CTF_Map.txt")]
        public string BackupFile_CTF_Inc {
            get {
                return ((string)(this["BackupFile_CTF_Inc"]));
            }
            set {
                this["BackupFile_CTF_Inc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999999CommonWords.txt")]
        public string BackupFile_CommonWords {
            get {
                return ((string)(this["BackupFile_CommonWords"]));
            }
            set {
                this["BackupFile_CommonWords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999999SubjectEncoding.json")]
        public string FileName_SubjectEncoding {
            get {
                return ((string)(this["FileName_SubjectEncoding"]));
            }
            set {
                this["FileName_SubjectEncoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999999Subject_Map.txt")]
        public string BackupFile_SubjectMap {
            get {
                return ((string)(this["BackupFile_SubjectMap"]));
            }
            set {
                this["BackupFile_SubjectMap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("999999EmailMoves.tsv")]
        public string FileName_MovedEmailsBackup {
            get {
                return ((string)(this["FileName_MovedEmailsBackup"]));
            }
            set {
                this["FileName_MovedEmailsBackup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999EmailSession.csv")]
        public string FileName_EmailSession {
            get {
                return ((string)(this["FileName_EmailSession"]));
            }
            set {
                this["FileName_EmailSession"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("99999EmailSessionTmp.csv")]
        public string FileName_EmailSessionTmp {
            get {
                return ((string)(this["FileName_EmailSessionTmp"]));
            }
            set {
                this["FileName_EmailSessionTmp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("999999EmailMoves.json")]
        public string FileName_MovedEmails {
            get {
                return ((string)(this["FileName_MovedEmails"]));
            }
            set {
                this["FileName_MovedEmails"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("999999PrefixList.json")]
        public string FileName_PrefixList {
            get {
                return ((string)(this["FileName_PrefixList"]));
            }
            set {
                this["FileName_PrefixList"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DarkMode {
            get {
                return ((bool)(this["DarkMode"]));
            }
            set {
                this["DarkMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("999999Filters.json")]
        public string FileName_Filters {
            get {
                return ((string)(this["FileName_Filters"]));
            }
            set {
                this["FileName_Filters"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool SaveAttachments {
            get {
                return ((bool)(this["SaveAttachments"]));
            }
            set {
                this["SaveAttachments"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool MoveEntireConversations {
            get {
                return ((bool)(this["MoveEntireConversations"]));
            }
            set {
                this["MoveEntireConversations"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SavePictures {
            get {
                return ((bool)(this["SavePictures"]));
            }
            set {
                this["SavePictures"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveEmailCopy {
            get {
                return ((bool)(this["SaveEmailCopy"]));
            }
            set {
                this["SaveEmailCopy"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("999999FilteredFolderScraping.json")]
        public string FileName_FilteredFolderScraping {
            get {
                return ((string)(this["FileName_FilteredFolderScraping"]));
            }
            set {
                this["FileName_FilteredFolderScraping"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("999999FolderRemap.json")]
        public string FileName_FolderRemap {
            get {
                return ((string)(this["FileName_FolderRemap"]));
            }
            set {
                this["FileName_FolderRemap"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("999999ClassifierManager.json")]
        public string File_ClassifierManager {
            get {
                return ((string)(this["File_ClassifierManager"]));
            }
            set {
                this["File_ClassifierManager"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999999emailInfo.json")]
        public string FileName_EmailInfoStaging {
            get {
                return ((string)(this["FileName_EmailInfoStaging"]));
            }
            set {
                this["FileName_EmailInfoStaging"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("999999ProgramDictionary.json")]
        public string FileName_ProgramDictionary {
            get {
                return ((string)(this["FileName_ProgramDictionary"]));
            }
            set {
                this["FileName_ProgramDictionary"] = value;
            }
        }
    }
}
