// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version:4.0.30319.42000
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System.Runtime.CompilerServices;



namespace TaskMaster.My
{

    [CompilerGenerated()]
    [System.CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0")]
    [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
    public sealed partial class MySettings : System.Configuration.ApplicationSettingsBase
    {

        private static MySettings defaultInstance = (MySettings)Synchronized(new MySettings());

        #region My.Settings Auto-Save Functionality
        /* TODO ERROR: Skipped IfDirectiveTrivia
        #If _MyType = "WindowsForms" Then
        *//* TODO ERROR: Skipped DisabledTextTrivia
            Private Shared addedHandler As Boolean

            Private Shared addedHandlerLockObject As New Object

            <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
            Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
                If My.Application.SaveMySettingsOnExit Then
                    My.Settings.Save()
                End If
            End Sub
        *//* TODO ERROR: Skipped EndIfDirectiveTrivia
        #End If
        */
        #endregion

        public static MySettings Default
        {
            get
            {

                /* TODO ERROR: Skipped IfDirectiveTrivia
                #If _MyType = "WindowsForms" Then
                *//* TODO ERROR: Skipped DisabledTextTrivia
                               If Not addedHandler Then
                                    SyncLock addedHandlerLockObject
                                        If Not addedHandler Then
                                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                                            addedHandler = True
                                        End If
                                    End SyncLock
                                End If
                *//* TODO ERROR: Skipped EndIfDirectiveTrivia
                #End If
                */
                return defaultInstance;
            }
        }

        [System.Configuration.ApplicationScopedSetting()]
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0")]
        public long MaxToDo
        {
            get
            {
                return Conversions.ToLong(this["MaxToDo"]);
            }
        }

        [System.Configuration.UserScopedSetting()]
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("15")]
        public int Default_Task_Length
        {
            get
            {
                return Conversions.ToInteger(this["Default_Task_Length"]);
            }
            set
            {
                this["Default_Task_Length"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("Tag PPL ")]
        public string Prefix_People
        {
            get
            {
                return Conversions.ToString(this["Prefix_People"]);
            }
            set
            {
                this["Prefix_People"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("_@")]
        public string Prefix_Context
        {
            get
            {
                return Conversions.ToString(this["Prefix_Context"]);
            }
            set
            {
                this["Prefix_Context"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("Tag TOPIC ")]
        public string Prefix_Topic
        {
            get
            {
                return Conversions.ToString(this["Prefix_Topic"]);
            }
            set
            {
                this["Prefix_Topic"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("Tag PROJECT ")]
        public string Prefix_Project
        {
            get
            {
                return Conversions.ToString(this["Prefix_Project"]);
            }
            set
            {
                this["Prefix_Project"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("Tag A Top Priority Today")]
        public string Prefix_Today
        {
            get
            {
                return Conversions.ToString(this["Prefix_Today"]);
            }
            set
            {
                this["Prefix_Today"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("Tag Bullpin Priorities")]
        public string Prefix_Bullpin
        {
            get
            {
                return Conversions.ToString(this["Prefix_Bullpin"]);
            }
            set
            {
                this["Prefix_Bullpin"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("Tag KB ")]
        public string Prefix_KB
        {
            get
            {
                return Conversions.ToString(this["Prefix_KB"]);
            }
            set
            {
                this["Prefix_KB"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("Archive")]
        public string Archive_Root
        {
            get
            {
                return Conversions.ToString(this["Archive_Root"]);
            }
            set
            {
                this["Archive_Root"] = value;
            }
        }

        [System.Configuration.ApplicationScopedSetting()]
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("ProjInfo.bin")]
        public string FileName_ProjInfo
        {
            get
            {
                return Conversions.ToString(this["FileName_ProjInfo"]);
            }
        }

        [System.Configuration.ApplicationScopedSetting()]
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("pplkey.json")]
        public string FilenameDictPpl
        {
            get
            {
                return Conversions.ToString(this["FilenameDictPpl"]);
            }
        }

        [System.Configuration.ApplicationScopedSetting()]
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("UsedIDList.bin")]
        public string FileName_IDList
        {
            get
            {
                return Conversions.ToString(this["FileName_IDList"]);
            }
        }

        [System.Configuration.UserScopedSetting()]
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("dictRemap.csv")]
        public string FileName_DictRemap
        {
            get
            {
                return Conversions.ToString(this["FileName_DictRemap"]);
            }
            set
            {
                this["FileName_DictRemap"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("3")]
        public long ConversationExponent
        {
            get
            {
                return Conversions.ToLong(this["ConversationExponent"]);
            }
            set
            {
                this["ConversationExponent"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("10000")]
        public string ConversationWeight
        {
            get
            {
                return Conversions.ToString(this["ConversationWeight"]);
            }
            set
            {
                this["ConversationWeight"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("1")]
        public string SubjectExponent
        {
            get
            {
                return Conversions.ToString(this["SubjectExponent"]);
            }
            set
            {
                this["SubjectExponent"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("-1")]
        public string SmithWatterman_GapPenalty
        {
            get
            {
                return Conversions.ToString(this["SmithWatterman_GapPenalty"]);
            }
            set
            {
                this["SmithWatterman_GapPenalty"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("1")]
        public string SmithWatterman_MatchScore
        {
            get
            {
                return Conversions.ToString(this["SmithWatterman_MatchScore"]);
            }
            set
            {
                this["SmithWatterman_MatchScore"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("0")]
        public string SmithWatterman_MismatchScore
        {
            get
            {
                return Conversions.ToString(this["SmithWatterman_MismatchScore"]);
            }
            set
            {
                this["SmithWatterman_MismatchScore"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("5")]
        public long MaxRecents
        {
            get
            {
                return Conversions.ToLong(this["MaxRecents"]);
            }
            set
            {
                this["MaxRecents"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("9999999RecentsFile.json")]
        public string FileName_Recents
        {
            get
            {
                return Conversions.ToString(this["FileName_Recents"]);
            }
            set
            {
                this["FileName_Recents"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("9999999CTF_Inc.json")]
        public string File_CTF_Inc
        {
            get
            {
                return Conversions.ToString(this["File_CTF_Inc"]);
            }
            set
            {
                this["File_CTF_Inc"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("9999999CTF_Map.json")]
        public string File_CTF_Map
        {
            get
            {
                return Conversions.ToString(this["File_CTF_Map"]);
            }
            set
            {
                this["File_CTF_Map"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("9999999Subject_Map.json")]
        public string File_Subject_Map
        {
            get
            {
                return Conversions.ToString(this["File_Subject_Map"]);
            }
            set
            {
                this["File_Subject_Map"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("9999999CommonWords.json")]
        public string File_Common_Words
        {
            get
            {
                return Conversions.ToString(this["File_Common_Words"]);
            }
            set
            {
                this["File_Common_Words"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("999999ConditionalReminders.json")]
        public string File_ConditionalReminders
        {
            get
            {
                return Conversions.ToString(this["File_ConditionalReminders"]);
            }
            set
            {
                this["File_ConditionalReminders"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("999999CategoryFilters.json")]
        public string FileName_CategoryFilters
        {
            get
            {
                return Conversions.ToString(this["FileName_CategoryFilters"]);
            }
            set
            {
                this["FileName_CategoryFilters"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("Main View")]
        public string View_Wide
        {
            get
            {
                return Conversions.ToString(this["View_Wide"]);
            }
            set
            {
                this["View_Wide"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("Compact")]
        public string View_Compact
        {
            get
            {
                return Conversions.ToString(this["View_Compact"]);
            }
            set
            {
                this["View_Compact"] = value;
            }
        }

        [System.Configuration.UserScopedSetting()]
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.Configuration.DefaultSettingValue("9999999CTF_Inc.txt")]
        public string BackupFile_CTF_Inc
        {
            get
            {
                return Conversions.ToString(this["BackupFile_CTF_Inc"]);
            }
            set
            {
                this["BackupFile_CTF_Inc"] = value;
            }
        }
    }
}

namespace TaskMaster.My
{

    [HideModuleName()]
    [System.Diagnostics.DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal static class MySettingsProperty
    {

        [System.ComponentModel.Design.HelpKeyword("My.Settings")]
        internal static MySettings Settings
        {
            get
            {
                return MySettings.Default;
            }
        }
    }
}