'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.5.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Public NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(sender As Global.System.Object, e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public ReadOnly Property MaxToDo() As Long
            Get
                Return CType(Me("MaxToDo"),Long)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("15")>  _
        Public Property Default_Task_Length() As Integer
            Get
                Return CType(Me("Default_Task_Length"),Integer)
            End Get
            Set
                Me("Default_Task_Length") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Tag PPL ")>  _
        Public Property Prefix_People() As String
            Get
                Return CType(Me("Prefix_People"),String)
            End Get
            Set
                Me("Prefix_People") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("_@")>  _
        Public Property Prefix_Context() As String
            Get
                Return CType(Me("Prefix_Context"),String)
            End Get
            Set
                Me("Prefix_Context") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Tag TOPIC ")>  _
        Public Property Prefix_Topic() As String
            Get
                Return CType(Me("Prefix_Topic"),String)
            End Get
            Set
                Me("Prefix_Topic") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Tag PROJECT ")>  _
        Public Property Prefix_Project() As String
            Get
                Return CType(Me("Prefix_Project"),String)
            End Get
            Set
                Me("Prefix_Project") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Tag A Top Priority Today")>  _
        Public Property Prefix_Today() As String
            Get
                Return CType(Me("Prefix_Today"),String)
            End Get
            Set
                Me("Prefix_Today") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Tag Bullpin Priorities")>  _
        Public Property Prefix_Bullpin() As String
            Get
                Return CType(Me("Prefix_Bullpin"),String)
            End Get
            Set
                Me("Prefix_Bullpin") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Tag KB ")>  _
        Public Property Prefix_KB() As String
            Get
                Return CType(Me("Prefix_KB"),String)
            End Get
            Set
                Me("Prefix_KB") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Archive")>  _
        Public Property Archive_Root() As String
            Get
                Return CType(Me("Archive_Root"),String)
            End Get
            Set
                Me("Archive_Root") = value
            End Set
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("ProjInfo.bin")>  _
        Public ReadOnly Property FileName_ProjInfo() As String
            Get
                Return CType(Me("FileName_ProjInfo"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("pplkey.json")>  _
        Public ReadOnly Property FilenameDictPpl() As String
            Get
                Return CType(Me("FilenameDictPpl"),String)
            End Get
        End Property
        
        <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("UsedIDList.bin")>  _
        Public ReadOnly Property FileName_IDList() As String
            Get
                Return CType(Me("FileName_IDList"),String)
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("dictRemap.csv")>  _
        Public Property FileName_DictRemap() As String
            Get
                Return CType(Me("FileName_DictRemap"),String)
            End Get
            Set
                Me("FileName_DictRemap") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
        Public Property ConversationExponent() As Long
            Get
                Return CType(Me("ConversationExponent"),Long)
            End Get
            Set
                Me("ConversationExponent") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10000")>  _
        Public Property ConversationWeight() As String
            Get
                Return CType(Me("ConversationWeight"),String)
            End Get
            Set
                Me("ConversationWeight") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property SubjectExponent() As String
            Get
                Return CType(Me("SubjectExponent"),String)
            End Get
            Set
                Me("SubjectExponent") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-1")>  _
        Public Property SmithWatterman_GapPenalty() As String
            Get
                Return CType(Me("SmithWatterman_GapPenalty"),String)
            End Get
            Set
                Me("SmithWatterman_GapPenalty") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
        Public Property SmithWatterman_MatchScore() As String
            Get
                Return CType(Me("SmithWatterman_MatchScore"),String)
            End Get
            Set
                Me("SmithWatterman_MatchScore") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property SmithWatterman_MismatchScore() As String
            Get
                Return CType(Me("SmithWatterman_MismatchScore"),String)
            End Get
            Set
                Me("SmithWatterman_MismatchScore") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("5")>  _
        Public Property MaxRecents() As Long
            Get
                Return CType(Me("MaxRecents"),Long)
            End Get
            Set
                Me("MaxRecents") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9999999RecentsFile.json")>  _
        Public Property FileName_Recents() As String
            Get
                Return CType(Me("FileName_Recents"),String)
            End Get
            Set
                Me("FileName_Recents") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9999999CTF_Inc.json")>  _
        Public Property File_CTF_Inc() As String
            Get
                Return CType(Me("File_CTF_Inc"),String)
            End Get
            Set
                Me("File_CTF_Inc") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9999999CTF_Map.json")>  _
        Public Property File_CTF_Map() As String
            Get
                Return CType(Me("File_CTF_Map"),String)
            End Get
            Set
                Me("File_CTF_Map") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9999999Subject_Map.json")>  _
        Public Property File_Subject_Map() As String
            Get
                Return CType(Me("File_Subject_Map"),String)
            End Get
            Set
                Me("File_Subject_Map") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9999999CommonWords.json")>  _
        Public Property File_Common_Words() As String
            Get
                Return CType(Me("File_Common_Words"),String)
            End Get
            Set
                Me("File_Common_Words") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("999999ConditionalReminders.json")>  _
        Public Property File_ConditionalReminders() As String
            Get
                Return CType(Me("File_ConditionalReminders"),String)
            End Get
            Set
                Me("File_ConditionalReminders") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("999999CategoryFilters.json")>  _
        Public Property FileName_CategoryFilters() As String
            Get
                Return CType(Me("FileName_CategoryFilters"),String)
            End Get
            Set
                Me("FileName_CategoryFilters") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Main View")>  _
        Public Property View_Wide() As String
            Get
                Return CType(Me("View_Wide"),String)
            End Get
            Set
                Me("View_Wide") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Compact")>  _
        Public Property View_Compact() As String
            Get
                Return CType(Me("View_Compact"),String)
            End Get
            Set
                Me("View_Compact") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("9999999CTF_Inc.txt")>  _
        Public Property BackupFile_CTF_Inc() As String
            Get
                Return CType(Me("BackupFile_CTF_Inc"),String)
            End Get
            Set
                Me("BackupFile_CTF_Inc") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.TaskMaster.My.MySettings
            Get
                Return Global.TaskMaster.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
