//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoModel.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.8.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tag PPL ")]
        public string Prefix_People {
            get {
                return ((string)(this["Prefix_People"]));
            }
            set {
                this["Prefix_People"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_@")]
        public string Prefix_Context {
            get {
                return ((string)(this["Prefix_Context"]));
            }
            set {
                this["Prefix_Context"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tag TOPIC ")]
        public string Prefix_Topic {
            get {
                return ((string)(this["Prefix_Topic"]));
            }
            set {
                this["Prefix_Topic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tag PROJECT ")]
        public string Prefix_Project {
            get {
                return ((string)(this["Prefix_Project"]));
            }
            set {
                this["Prefix_Project"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tag A Top Priority Today")]
        public string Prefix_Today {
            get {
                return ((string)(this["Prefix_Today"]));
            }
            set {
                this["Prefix_Today"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tag Bullpin Priorities")]
        public string Prefix_Bullpin {
            get {
                return ((string)(this["Prefix_Bullpin"]));
            }
            set {
                this["Prefix_Bullpin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tag KB ")]
        public string Prefix_KB {
            get {
                return ((string)(this["Prefix_KB"]));
            }
            set {
                this["Prefix_KB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int Default_Task_Length {
            get {
                return ((int)(this["Default_Task_Length"]));
            }
            set {
                this["Default_Task_Length"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int MaxToDo {
            get {
                return ((int)(this["MaxToDo"]));
            }
            set {
                this["MaxToDo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int MaxLengthOfID {
            get {
                return ((int)(this["MaxLengthOfID"]));
            }
            set {
                this["MaxLengthOfID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int MaxFolders_ConvID {
            get {
                return ((int)(this["MaxFolders_ConvID"]));
            }
            set {
                this["MaxFolders_ConvID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999999CTF_Inc.txt")]
        public string File_CTF_Inc {
            get {
                return ((string)(this["File_CTF_Inc"]));
            }
            set {
                this["File_CTF_Inc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999999CTF_Map.txt")]
        public string File_CTF_Map {
            get {
                return ((string)(this["File_CTF_Map"]));
            }
            set {
                this["File_CTF_Map"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999999Subject_Map.txt")]
        public string File_Subject_Map {
            get {
                return ((string)(this["File_Subject_Map"]));
            }
            set {
                this["File_Subject_Map"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("9999999CommonWords.txt")]
        public string File_Common_Words {
            get {
                return ((string)(this["File_Common_Words"]));
            }
            set {
                this["File_Common_Words"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("999999ConditionalReminders.txt")]
        public string File_ConditionalReminders {
            get {
                return ((string)(this["File_ConditionalReminders"]));
            }
            set {
                this["File_ConditionalReminders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int MaxFolders_Subject {
            get {
                return ((int)(this["MaxFolders_Subject"]));
            }
            set {
                this["MaxFolders_Subject"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int MaxSuggestions {
            get {
                return ((int)(this["MaxSuggestions"]));
            }
            set {
                this["MaxSuggestions"] = value;
            }
        }
    }
}
