//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilitiesCS.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.11.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tag PPL ")]
        public string Prefix_People {
            get {
                return ((string)(this["Prefix_People"]));
            }
            set {
                this["Prefix_People"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("_@")]
        public string Prefix_Context {
            get {
                return ((string)(this["Prefix_Context"]));
            }
            set {
                this["Prefix_Context"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tag TOPIC ")]
        public string Prefix_Topic {
            get {
                return ((string)(this["Prefix_Topic"]));
            }
            set {
                this["Prefix_Topic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tag PROJECT ")]
        public string Prefix_Project {
            get {
                return ((string)(this["Prefix_Project"]));
            }
            set {
                this["Prefix_Project"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tag A Top Priority Today")]
        public string Prefix_Today {
            get {
                return ((string)(this["Prefix_Today"]));
            }
            set {
                this["Prefix_Today"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tag Bullpin Priorities")]
        public string Prefix_Bullpin {
            get {
                return ((string)(this["Prefix_Bullpin"]));
            }
            set {
                this["Prefix_Bullpin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Tag KB ")]
        public string Prefix_KB {
            get {
                return ((string)(this["Prefix_KB"]));
            }
            set {
                this["Prefix_KB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("TagProgram")]
        public string Prefix_Program {
            get {
                return ((string)(this["Prefix_Program"]));
            }
            set {
                this["Prefix_Program"] = value;
            }
        }
    }
}
