// ------------------------------------------------------------------------------
// <auto-generated>
// This code was generated by a tool.
// Runtime Version:4.0.30319.42000
// 
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Runtime.CompilerServices;
using Outlook = Microsoft.Office.Interop.Outlook;

namespace TaskMaster
{



    /// 
    [Microsoft.VisualStudio.Tools.Applications.Runtime.StartupObject(0)]
    [System.Security.Permissions.PermissionSet(System.Security.Permissions.SecurityAction.Demand, Name = "FullTrust")]
    public sealed partial class ThisAddIn : Microsoft.Office.Tools.Outlook.OutlookAddInBase
    {

        private Microsoft.Office.Tools.CustomTaskPaneCollection _CustomTaskPanes;

        internal Microsoft.Office.Tools.CustomTaskPaneCollection CustomTaskPanes
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _CustomTaskPanes;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                _CustomTaskPanes = value;
            }
        }

        [System.CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        private Outlook.Application _Application;

        [System.CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        internal Outlook.Application Application
        {
            [MethodImpl(MethodImplOptions.Synchronized)]
            get
            {
                return _Application;
            }

            [MethodImpl(MethodImplOptions.Synchronized)]
            set
            {
                _Application = value;
            }
        }

        /// 
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        public ThisAddIn(Microsoft.Office.Tools.Outlook.Factory factory, IServiceProvider serviceProvider) : base(factory, serviceProvider, "AddIn", "ThisAddIn")
        {
            Startup += (_, __) => ThisAddIn_Startup();
            OlToDoItems.ItemAdd += OlToDoItems_ItemAdd;
            OlToDoItems.ItemChange += OlToDoItems_ItemChange;
            Globals.Factory = factory;
        }

        /// 
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void Initialize()
        {
            base.Initialize();
            Application = GetHostItem<Outlook.Application>(typeof(Outlook.Application), "Application");
            Globals.ThisAddIn = this;
            System.Windows.Forms.Application.EnableVisualStyles();
            InitializeCachedData();
            InitializeControls();
            InitializeComponents();
            InitializeData();
        }

        /// 
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void FinishInitialization()
        {
            OnStartup();
        }

        /// 
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void InitializeDataBindings()
        {
            BeginInitialization();
            BindToData();
            EndInitialization();
        }

        /// 
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeCachedData()
        {
            if (DataHost is null)
            {
                return;
            }
            if (DataHost.IsCacheInitialized)
            {
                DataHost.FillCachedData(this);
            }
        }

        /// 
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeData()
        {
        }

        /// 
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        private void BindToData()
        {
        }

        /// 
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StartCaching(string MemberName)
        {
            DataHost.StartCaching(this, MemberName);
        }

        /// 
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        private void StopCaching(string MemberName)
        {
            DataHost.StopCaching(this, MemberName);
        }

        /// 
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool IsCached(string MemberName)
        {
            return DataHost.IsCached(this, MemberName);
        }

        /// 
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        private void BeginInitialization()
        {
            BeginInit();
            CustomTaskPanes.BeginInit();
        }

        /// 
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        private void EndInitialization()
        {
            CustomTaskPanes.EndInit();
            EndInit();
        }

        /// 
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeControls()
        {
            CustomTaskPanes = Globals.Factory.CreateCustomTaskPaneCollection(null, null, "CustomTaskPanes", "CustomTaskPanes", this);
        }

        /// 
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        private void InitializeComponents()
        {
        }

        /// 
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Advanced)]
        private bool NeedsFill(string MemberName)
        {
            return DataHost.NeedsFill(this, MemberName);
        }

        /// 
        [System.Diagnostics.DebuggerNonUserCode()]
        [System.CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
        [System.ComponentModel.EditorBrowsable(System.ComponentModel.EditorBrowsableState.Never)]
        protected override void OnShutdown()
        {
            CustomTaskPanes.Dispose();
            base.OnShutdown();
        }
    }

    /// 
    [System.Diagnostics.DebuggerNonUserCode()]
    [System.CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
    internal sealed partial class Globals
    {

        /// 
        private Globals() : base()
        {
        }

        private static ThisAddIn _ThisAddIn;

        private static Microsoft.Office.Tools.Outlook.Factory _factory;

        private static ThisRibbonCollection _ThisRibbonCollection;

        private static ThisFormRegionCollection _ThisFormRegionCollection;

        internal static ThisAddIn ThisAddIn
        {
            get
            {
                return _ThisAddIn;
            }
            set
            {
                if (_ThisAddIn is null)
                {
                    _ThisAddIn = value;
                }
                else
                {
                    throw new NotSupportedException();
                }
            }
        }

        internal static Microsoft.Office.Tools.Outlook.Factory Factory
        {
            get
            {
                return _factory;
            }
            set
            {
                if (_factory is null)
                {
                    _factory = value;
                }
                else
                {
                    throw new NotSupportedException();
                }
            }
        }

        internal static ThisRibbonCollection Ribbons
        {
            get
            {
                if (_ThisRibbonCollection is null)
                {
                    _ThisRibbonCollection = new ThisRibbonCollection(_factory.GetRibbonFactory());
                }
                return _ThisRibbonCollection;
            }
        }

        internal static ThisFormRegionCollection FormRegions
        {
            get
            {
                if (_ThisFormRegionCollection is null)
                {
                    _ThisFormRegionCollection = new ThisFormRegionCollection(ThisAddIn.GetFormRegions());
                }
                return _ThisFormRegionCollection;
            }
        }
    }

    /// 
    [System.Diagnostics.DebuggerNonUserCode()]
    [System.CodeDom.Compiler.GeneratedCode("Microsoft.VisualStudio.Tools.Office.ProgrammingModel.dll", "16.0.0.0")]
    internal sealed partial class ThisRibbonCollection : Microsoft.Office.Tools.Ribbon.RibbonCollectionBase
    {

        /// 
        internal ThisRibbonCollection(Microsoft.Office.Tools.Ribbon.RibbonFactory factory) : base(factory)
        {
        }

        internal ThisRibbonCollection this[Outlook.Inspector inspector]
        {
            get
            {
                return GetRibbonContextCollection<ThisRibbonCollection>(inspector);
            }
        }

        internal ThisRibbonCollection this[Outlook.Explorer explorer]
        {
            get
            {
                return GetRibbonContextCollection<ThisRibbonCollection>(explorer);
            }
        }
    }

    /// 
    [System.Diagnostics.DebuggerNonUserCode()]
    internal sealed partial class ThisFormRegionCollection : Microsoft.Office.Tools.Outlook.FormRegionCollectionBase
    {

        /// 
        public ThisFormRegionCollection(IList<Microsoft.Office.Tools.Outlook.IFormRegion> list) : base(list)
        {
        }

        internal WindowFormRegionCollection this[Outlook.Explorer explorer]
        {
            get
            {
                return (WindowFormRegionCollection)Globals.ThisAddIn.GetFormRegions(explorer, typeof(WindowFormRegionCollection));
            }
        }

        internal WindowFormRegionCollection this[Outlook.Inspector inspector]
        {

            get
            {
                return (WindowFormRegionCollection)Globals.ThisAddIn.GetFormRegions(inspector, typeof(WindowFormRegionCollection));
            }
        }
    }

    /// 
    [System.Diagnostics.DebuggerNonUserCode()]
    internal sealed partial class WindowFormRegionCollection : Microsoft.Office.Tools.Outlook.FormRegionCollectionBase
    {

        /// 
        public WindowFormRegionCollection(IList<Microsoft.Office.Tools.Outlook.IFormRegion> list) : base(list)
        {
        }
    }
}