using System.Collections.Generic;

namespace ToDoModel
{
    public static class Load_CCO_Categories
    {
        public static List<string> CCOCatList_Load()
        {
            var _listCCO = new List<string>();

            _listCCO.Add("Tag PROJECT 31 Conectados");
            _listCCO.Add("Tag PROJECT 31 Digital Architecture");
            _listCCO.Add("Tag PROJECT 31 Digital Center Expansion BCC");
            _listCCO.Add("Tag PROJECT 31 eGTM");
            _listCCO.Add("Tag PROJECT 31 iVend");
            _listCCO.Add("Tag PROJECT 31 Perfect Store");
            _listCCO.Add("Tag PROJECT 31 RM Analytics Simulator");
            _listCCO.Add("Tag PROJECT 31 White Swan TPM TPO");
            _listCCO.Add("Tag PROJECT 31Marketing Consumer DNA");
            _listCCO.Add("Tag PROJECT 31Marketing Mix Modeling and ROI Media MMM");
            _listCCO.Add("Tag PROJECT 32 Marketing As A Function");
            _listCCO.Add("Tag PROJECT 33 GBS");
            _listCCO.Add("Tag PROJECT 33 POS Central Design");
            _listCCO.Add("Tag PROJECT 33 RIC Route Enginnering Center");
            _listCCO.Add("Tag PROJECT 33 Working A&M");
            _listCCO.Add("Tag PROJECT 34 GTM Brazil - Ilumina");
            _listCCO.Add("Tag PROJECT 35 CCO Org Design and Functions");
            _listCCO.Add("Tag PROJECT 36 Coronavirus Response");
            _listCCO.Add("Tag PROJECT 37 OT Capability");
            _listCCO.Add("Tag PROJECT 41 Functional - Duties");
            _listCCO.Add("Tag PROJECT 41 Functional - Learning Agenda");
            _listCCO.Add("Tag PROJECT 41 Functional - UEFA UCLF Champions League 2020");
            _listCCO.Add("Tag PROJECT 42 Planning - AOP 2019");
            _listCCO.Add("Tag PROJECT 42 Planning - AOP 2020");
            _listCCO.Add("Tag PROJECT 42 Planning - AOP 2021");
            _listCCO.Add("Tag PROJECT 42 Planning - COVID Replan");
            _listCCO.Add("Tag PROJECT 42 Planning - POR");
            _listCCO.Add("Tag PROJECT 42 Planning - PSP 2020");
            _listCCO.Add("Tag PROJECT 43 Other CCO");
            _listCCO.Add("Tag PROJECT 43 Represent Sector Globally");
            _listCCO.Add("Tag PROJECT 43 Routine - 1w1");
            _listCCO.Add("Tag PROJECT 43 Routine - Approvals");
            _listCCO.Add("Tag PROJECT 43 Routine - Improve Personal Efficiency / Effectiveness");
            _listCCO.Add("Tag PROJECT 43 Routine - LATAM Excom Duties");
            _listCCO.Add("Tag PROJECT 43 Routine - Market Visits / Stakeholder Wiring");
            _listCCO.Add("Tag PROJECT 43 Routine - Other Tasks");
            _listCCO.Add("Tag PROJECT 43 Routine - People Process");
            _listCCO.Add("Tag PROJECT 43 Routine - Plan Calendar");
            _listCCO.Add("Tag PROJECT 43 Routine - Reading");
            _listCCO.Add("Tag PROJECT 43 Routine - Team Leadership Duties");
            _listCCO.Add("Tag PROJECT 43 Routine - Training");
            _listCCO.Add("Tag PROJECT 98 Atlantic");
            _listCCO.Add("Tag PROJECT 98 Capacity Investments");
            _listCCO.Add("Tag PROJECT 98 Corporate Audit");
            _listCCO.Add("Tag PROJECT 98 Costa Rica Strategy");
            _listCCO.Add("Tag PROJECT 98 Dominican Republic TAP");
            _listCCO.Add("Tag PROJECT 98 Gira Caricam");
            _listCCO.Add("Tag PROJECT 98 Gira Caricam 2019");
            _listCCO.Add("Tag PROJECT 98 Guatemala Turnaround");
            _listCCO.Add("Tag PROJECT 98 H1 Travel Agenda");
            _listCCO.Add("Tag PROJECT 98 Imports Agile Stage Gate");
            _listCCO.Add("Tag PROJECT 98 INSEAD IPP Integrating Performance and Progress");
            _listCCO.Add("Tag PROJECT 98 ISCP Horizon");
            _listCCO.Add("Tag PROJECT 98 Kendall Awards");
            _listCCO.Add("Tag PROJECT 98 MDM");
            _listCCO.Add("Tag PROJECT 98 Oats War Games");
            _listCCO.Add("Tag PROJECT 98 OT / CATMAN CAPABILITY");
            _listCCO.Add("Tag PROJECT 98 Other Caricam");
            _listCCO.Add("Tag PROJECT 98 Parallel Imports");
            _listCCO.Add("Tag PROJECT 98 Planning - AOP 2019");
            _listCCO.Add("Tag PROJECT 98 Ramon Visit To Guatemala");
            _listCCO.Add("Tag PROJECT 98 Revenue Management SLAM Panama");
            _listCCO.Add("Tag PROJECT 98 SAP Leveling");
            _listCCO.Add("Tag PROJECT 98 Splenda Panama DTS");
            _listCCO.Add("Tag PROJECT 98 Visits 181106 Brian Newman Johannes Guatemala");
            _listCCO.Add("Tag PROJECT Personal - Other");
            _listCCO.Add("Tag PROJECT Relocation");
            _listCCO.Add("Tag PROJECT Taxes 2016");
            _listCCO.Add("Tag PROJECT Taxes 2017");
            _listCCO.Add("Tag PROJECT Taxes 2018");
            _listCCO.Add("Tag PPL Monica Bauer");
            _listCCO.Add("Tag PPL Martin Ribichich");
            _listCCO.Add("Tag PPL Luz Gossmann");
            _listCCO.Add("Tag PPL Isaias Martinez");
            _listCCO.Add("Tag PPL Claudia Olivos");
            _listCCO.Add("Tag PPL Veronica Riojas");
            _listCCO.Add("Tag PPL Bennett Price");
            _listCCO.Add("Tag PPL Alejandro Puig");
            _listCCO.Add("Tag PPL Hernan Tantardini");
            _listCCO.Add("Tag PPL Dani Cachich");
            _listCCO.Add("Tag PPL Raul Cortes");
            _listCCO.Add("Tag PPL Maria Emiliana Rodriguez");
            _listCCO.Add("Tag PPL Gabriela Alves");
            _listCCO.Add("Tag PPL Claus Hanspach");
            _listCCO.Add("Tag PPL Luis Ruben Gutierrez");
            _listCCO.Add("Tag PPL Karla Halley");
            _listCCO.Add("Tag PPL Adalberto Aguilar");
            _listCCO.Add("Tag PPL Todd Squarek");
            _listCCO.Add("Tag PPL Gabriela Garciacortes");
            _listCCO.Add("Tag PPL Lily Zaidman");
            _listCCO.Add("Tag PPL Erich Gamper");
            _listCCO.Add("Tag PPL Georgina Rodriguez");
            _listCCO.Add("Tag PPL Ana Henao");
            _listCCO.Add("Tag PPL Eduardo Real");
            _listCCO.Add("Tag PPL Salvador Hernandez");
            _listCCO.Add("Tag PPL Omar Gonzalez");
            _listCCO.Add("Tag PPL Arnab Sinha");
            _listCCO.Add("Tag PPL Parinya Kitjatanapan");
            _listCCO.Add("Tag PPL Lucas Ciccarelli");
            _listCCO.Add("Tag PPL Ivonne Dominguez");
            _listCCO.Add("Tag PPL Carlos DeLascurain");
            _listCCO.Add("Tag PPL Carlos SanchezAbril");
            _listCCO.Add("Tag PPL Gerardo Diaz de Leon");
            _listCCO.Add("Tag PPL Cristina Lou");
            _listCCO.Add("Tag PPL Eric Melis");
            _listCCO.Add("Tag PPL Harry Walsh");
            _listCCO.Add("Tag PPL LATAM EXCOM");
            _listCCO.Add("Tag PPL Carolina Moreno");
            _listCCO.Add("Tag PPL Rodolfo Portillo");
            _listCCO.Add("Tag PPL Triana Vazquez");
            _listCCO.Add("Tag PPL Janine Wacklawski");
            _listCCO.Add("Tag PPL Victor Hugo Gonzalez");
            _listCCO.Add("Tag PPL Vikram Somaya");
            _listCCO.Add("Tag PPL Andrew Motz");
            _listCCO.Add("Tag PPL Joao Campos");
            _listCCO.Add("Tag PPL Federico Lamberti");
            _listCCO.Add("Tag PPL Raul Bribiesca");
            _listCCO.Add("Tag PPL Dennis Furnis");
            _listCCO.Add("Tag PPL Beatriz Tilkian");
            _listCCO.Add("Tag PPL Erica Diago");
            _listCCO.Add("Tag PPL Begona Aristy");
            _listCCO.Add("Tag PPL Jose Cota");
            _listCCO.Add("Tag PPL Michelle Luciano");
            _listCCO.Add("Tag PPL Alejandra Noble");
            _listCCO.Add("Tag PPL Carlos Quintana");
            _listCCO.Add("Tag PPL Santiago Cota");
            _listCCO.Add("Tag PPL Carlos Pacheco");
            _listCCO.Add("Tag PPL Juan Zapiain");
            _listCCO.Add("Tag PPL Fernando Pliego");
            _listCCO.Add("Tag PPL David Kahn");
            _listCCO.Add("Tag PPL Ian Kahn");
            _listCCO.Add("Tag PPL Marco Viramontes");
            _listCCO.Add("Tag PPL Mauricio Nakaie");
            _listCCO.Add("Tag PPL Hernan Bazan");
            _listCCO.Add("Tag PPL Axelle Olivares");
            _listCCO.Add("Tag PPL Alejandro Romo");
            _listCCO.Add("Tag PPL Arturo Aviladominguez");
            _listCCO.Add("Tag PPL JoseMaria Chepe Mora");
            _listCCO.Add("Tag PPL Lalo Vidargas");
            _listCCO.Add("Tag PPL Dora Blanco");
            _listCCO.Add("Tag PPL Felipe Santanaruiz");
            _listCCO.Add("Tag PPL Joao Goncalves");
            _listCCO.Add("Tag PPL Paulina Corona");
            _listCCO.Add("Tag PPL Paula Santilli");
            _listCCO.Add("Tag PPL Gonzalo Muente");
            _listCCO.Add("Tag PPL Ricardo Arias");
            _listCCO.Add("Tag PPL Leonardo Aio");
            _listCCO.Add("Tag PPL Pedro Escalante");
            _listCCO.Add("Tag PPL Mauricio Degaray");
            _listCCO.Add("Tag PPL Michal Geller");
            _listCCO.Add("Tag PPL Raul Pedrique");
            _listCCO.Add("Tag PPL Miguel Olivares");
            _listCCO.Add("Tag PPL Chufi Zarate");
            _listCCO.Add("Tag PPL Carlos Eboli");
            _listCCO.Add("Tag PPL Erick Scheel");
            _listCCO.Add("Tag PPL Hector Ariel");
            _listCCO.Add("Tag PPL Paula Velazquez");
            _listCCO.Add("Tag PPL Manny Pineiro");
            _listCCO.Add("Tag PPL Ana Fleury");
            _listCCO.Add("Tag PPL Gibu Thomas");
            _listCCO.Add("Tag PPL Ezequiel Gomez");
            _listCCO.Add("Tag PPL Yolanda Lebron");
            _listCCO.Add("Tag PPL PWC");
            _listCCO.Add("Tag PPL Salomon Levy");
            _listCCO.Add("Tag PPL Juan Aude");
            _listCCO.Add("Tag PPL Catalina Casco");
            _listCCO.Add("Tag PPL Carlos Gonzalez");
            _listCCO.Add("Tag PPL Mike Roper");
            _listCCO.Add("Tag PPL Steve Gibson");
            _listCCO.Add("Tag PPL Ricardo Pimenta");
            _listCCO.Add("Tag PPL Lorena Segal");
            _listCCO.Add("Tag PPL Marjorie Delacruz");
            _listCCO.Add("Tag PPL Cristina Leo");
            _listCCO.Add("Tag PPL Ergun Gunay -> APAC");
            _listCCO.Add("Tag PPL Juancarlos Haro");
            _listCCO.Add("Tag PPL Ricardo Cuellar");
            _listCCO.Add("Tag PPL Roberto Martinez");
            _listCCO.Add("Tag PPL Glenda Pfirter");
            _listCCO.Add("Tag PPL Mimi Chen");
            _listCCO.Add("Tag PPL Lilly Yip");
            _listCCO.Add("Tag PPL Lucia Weymann");
            _listCCO.Add("Tag PPL Celso Borges");
            _listCCO.Add("Tag PPL Paulina Castillo");
            _listCCO.Add("Tag PPL Valeria Rivas");
            _listCCO.Add("Tag PPL Paco Cotera");
            _listCCO.Add("Tag PPL Carmela Rivero");
            _listCCO.Add("Tag PPL Monica Tenorio");
            _listCCO.Add("Tag PPL Fernando Mateos");

            return _listCCO;

        }



    }
}